#!/usr/bin/env python3
"""
DG Declaration Builder
=======================
Reads a DG cargo Annexure (Excel), optionally cross-verifies it against MSDS
and UN Certificate PDFs, groups product lines onto declarations using a
5-checkpoint sequence, and fills your own DGDI Excel template — one file per
declaration group — ready to submit to your shipping line.

The output is generated by editing your real template workbook in place
(openpyxl), so fonts, borders, merged cells, column widths and any embedded
letterhead/logo are preserved exactly. Only the specific data cells are
overwritten.

USAGE
-----
    python dg_declaration_builder.py \\
        --annexure Annexure.xlsx \\
        --template MANUAL_DGD1.xlsx \\
        --msds MSDS1.pdf MSDS2.pdf \\
        --certs CERT1.pdf CERT2.pdf \\
        --shipment shipment.json \\
        --out ./output

Run with --make-shipment-template to generate a blank shipment.json to fill in.
Run with --help for all options.
"""

import argparse
import json
import re
import sys
from datetime import date, datetime
from pathlib import Path

import openpyxl
import pdfplumber

# ============================================================================
# COLUMN FUZZY MATCHING
# ============================================================================

FIELD_SYNONYMS = {
    "materialDescription": ["materialdescription", "description", "productdescription", "itemdescription"],
    "unNumber": ["unnumber", "unno"],
    "psn": ["unpropershippingname", "propershippingname", "shippingname", "psn"],
    "hazClass": ["hazclass", "class", "hazardclass", "transporthazardclass"],
    "pkgGroup": ["pkggroup", "packinggroup", "packgroup", "unpackinggroup"],
    "marinePollutant": ["marinepollutant", "mp"],
    "flashPoint": ["flashpoint", "fp"],
    "unCertNo1": ["uncertificateno1", "uncertno1"],
    "unCertNoShort": ["uncertificateno", "uncertno"],
    "noOfBoxes": ["noofboxesdrums", "noofboxes", "outerpackages"],
    "noInTins": ["nointins", "noinctins", "noinstins", "notins", "innerpackages", "noincltins"],
    "grossWt": ["grosswtwithpelletwtinkg", "grosswtinkg", "grosswt"],
    "netWt": ["netwtinkg", "netwt"],
    "ems": ["ems"],
    "technicalName": ["technicalname"],
    "productCode": ["productcode"],
}
REQUIRED_FIELDS = [
    "materialDescription", "unNumber", "psn", "hazClass", "pkgGroup",
    "marinePollutant", "flashPoint", "unCertNo1", "noOfBoxes", "noInTins",
    "grossWt", "netWt",
]

CHECKPOINTS = [
    ("Flash point", "< 23\u00b0C / \u2265 23\u00b0C (threshold configurable)"),
    ("PSN name", "Unique proper shipping name"),
    ("Packing code", "1st chars: 4G / 1A1 / 1A2"),
    ("Marine pollutant", "YES / NO"),
    ("UN number", "Unique"),
]


def norm(s):
    return re.sub(r"[^a-z0-9]", "", str(s or "").lower())


def match_columns(headers):
    """Fuzzy-match a header row against the required/known field synonyms."""
    normed = [norm(h) for h in headers]
    used = set()
    result = {}
    for field, syns in FIELD_SYNONYMS.items():
        best = -1
        # exact match pass
        for syn in syns:
            for i, h in enumerate(normed):
                if h == syn and i not in used:
                    best = i
                    break
            if best != -1:
                break
        # substring pass
        if best == -1:
            for syn in syns:
                for i, h in enumerate(normed):
                    if syn in h and i not in used:
                        best = i
                        break
                if best != -1:
                    break
        if best != -1:
            result[field] = best
            used.add(best)
    return result


def pick_best_sheet(wb):
    """Scan every sheet's first few rows for the header row that best matches
    the required fields, and return (sheet_name, header_row_idx, col_map, score)."""
    best = {"name": None, "score": -1, "header_row": -1, "map": {}}
    for ws in wb.worksheets:
        rows = list(ws.iter_rows(min_row=1, max_row=5, values_only=True))
        for r_idx, row in enumerate(rows):
            headers = [("" if c is None else str(c)) for c in row]
            col_map = match_columns(headers)
            score = sum(1 for f in REQUIRED_FIELDS if f in col_map)
            if score > best["score"]:
                best = {"name": ws.title, "score": score, "header_row": r_idx, "map": col_map}
    return best


def _f(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return 0.0


def parse_annexure(path):
    """Parse the Annexure workbook. Returns (rows, sheet_name, col_map, score)."""
    wb = openpyxl.load_workbook(path, data_only=True)
    best = pick_best_sheet(wb)
    if best["name"] is None:
        return [], None, {}, 0
    ws = wb[best["name"]]
    col_map = best["map"]
    all_rows = list(ws.iter_rows(min_row=best["header_row"] + 2, values_only=True))

    def get(row, field):
        idx = col_map.get(field)
        return row[idx] if idx is not None and idx < len(row) else None

    rows = []
    for r in all_rows:
        material = get(r, "materialDescription")
        un = get(r, "unNumber")
        if not material or not un:
            continue
        if str(material).strip().upper() == "TOTAL":
            continue
        rows.append({
            "materialDescription": str(material).strip(),
            "unNumber": str(un).strip(),
            "psn": str(get(r, "psn") or "").strip(),
            "hazClass": str(get(r, "hazClass") or "").strip(),
            "pkgGroup": str(get(r, "pkgGroup") or "").strip(),
            "marinePollutant": str(get(r, "marinePollutant") or "").strip().upper(),
            "flashPoint": str(get(r, "flashPoint") or "").strip(),
            "unCertNo1": str(get(r, "unCertNo1") or "").strip(),
            "unCertNoShort": str(get(r, "unCertNoShort") or "").strip(),
            "noOfBoxes": _f(get(r, "noOfBoxes")),
            "noInTins": _f(get(r, "noInTins")),
            "grossWt": _f(get(r, "grossWt")),
            "netWt": _f(get(r, "netWt")),
            "ems": str(get(r, "ems") or "").strip(),
            "technicalName": str(get(r, "technicalName") or "").strip(),
            "productCode": str(get(r, "productCode") or "").strip(),
        })
    return rows, best["name"], col_map, best["score"]


# ============================================================================
# PDF TEXT EXTRACTION
# ============================================================================

def extract_pdf_text(path):
    text = []
    with pdfplumber.open(path) as pdf:
        for page in pdf.pages:
            t = page.extract_text() or ""
            text.append(t)
    return "\n".join(text)


# ============================================================================
# MSDS CROSS-VERIFICATION
# ============================================================================

def extract_msds_identifiers(text):
    ids = set()
    m = re.search(r"Product identifier\s*:?\s*\n?([A-Za-z0-9\-]{2,20})", text, re.I)
    if m:
        ids.add(m.group(1).strip())
    m = re.search(r"Other means of[\s\S]{0,20}identification\s*:?\s*\n?([0-9A-Za-z;,\s]{4,60})", text, re.I)
    if m:
        for tok in re.split(r"[;,]", m.group(1)):
            tok = tok.strip()
            if tok:
                ids.add(tok)
    return list(ids)


def match_msds_to_row(msds_text, row):
    ids = [norm(i) for i in extract_msds_identifiers(msds_text)]
    desc_norm = norm(row["materialDescription"])
    for idn in ids:
        if not idn:
            continue
        if idn in desc_norm or norm(row["productCode"]) == idn:
            return True
    return False


def get_section14_block(text):
    m = re.search(r"Section\s*14", text, re.I)
    if not m:
        return text
    after = text[m.start():]
    m2 = re.search(r"Section\s*1[56]", after, re.I)
    return after if not m2 else after[:m2.start()]


def extract_flash_number(s):
    m = re.search(r"-?\d+(\.\d+)?", str(s))
    return float(m.group(0)) if m else None


def verify_msds_against_row(msds_text, row):
    block = get_section14_block(msds_text)
    block_upper = block.upper()
    checks = []

    un_digits = re.sub(r"\D", "", row["unNumber"])
    checks.append({
        "field": "UN Number",
        "ok": bool(re.search(r"UN\s?0*" + re.escape(un_digits) + r"\b", block)),
        "expected": row["unNumber"],
    })

    psn_ok = bool(row["psn"]) and row["psn"].upper() in block_upper
    checks.append({"field": "Proper shipping name", "ok": psn_ok, "expected": row["psn"]})

    cls_token = row["hazClass"].replace(" ", "")
    cls_ok = bool(re.search(r"(^|[^0-9.])" + re.escape(cls_token) + r"([^0-9]|$)", block))
    checks.append({"field": "Hazard class", "ok": cls_ok, "expected": row["hazClass"]})

    pg_ok = bool(row["pkgGroup"]) and bool(re.search(r"\b" + re.escape(row["pkgGroup"].upper()) + r"\b", block_upper))
    checks.append({"field": "Packing group", "ok": pg_ok, "expected": row["pkgGroup"]})

    mp_expected = "YES" if row["marinePollutant"] == "YES" else "NO"
    mp_ok = ("YES" in block_upper) if mp_expected == "YES" else bool(re.search(r"\bNO\.?\b", block_upper))
    checks.append({"field": "Marine pollutant", "ok": mp_ok, "expected": mp_expected})

    fp_match = re.search(r"Flash point\s*:?[\s\S]{0,60}", msds_text, re.I)
    fp_msds = extract_flash_number(fp_match.group(0)) if fp_match else None
    fp_row = extract_flash_number(row["flashPoint"])
    fp_ok = (fp_msds is not None and fp_row is not None and abs(fp_msds - fp_row) <= 1.0)
    detail = row["flashPoint"] + (f" (MSDS: {fp_msds}\u00b0C)" if fp_msds is not None else " (not found in MSDS)")
    checks.append({"field": "Flash point", "ok": fp_ok, "expected": detail})

    return checks


# ============================================================================
# UN CERTIFICATE CROSS-VERIFICATION
# ============================================================================

MARKING_CODE_RE = re.compile(r"([0-9][A-Z][0-9A-Z]?/[A-Z]\s*[0-9*]+/S/[0-9A-Z*]+)", re.I)
MARKING_IND_RE = re.compile(r"(IND/(?:[A-Z]/)?[0-9]+)", re.I)
VALID_RE = re.compile(r"valid\s*upto\s*[:\-]?\s*(\d{1,2}\s+[A-Za-z]+\s+\d{4})", re.I)


def extract_cert_info(text):
    # The packing-code fragment (e.g. "4G/Y 18/S/25") and the "IND/xxxxx" ref
    # are searched independently and then combined: real-world PDF text
    # extraction often interleaves the "UN Marking alloted :" label between
    # the two value lines, so they can't be relied on to sit adjacent.
    code_m = MARKING_CODE_RE.search(text)
    ind_m = MARKING_IND_RE.search(text)
    if not code_m or not ind_m:
        return None
    code_part = re.sub(r"\s+", " ", code_m.group(1)).strip()
    full = f"{code_part} {ind_m.group(1)}"
    digits = re.search(r"(\d+)$", ind_m.group(1))
    digits = digits.group(1) if digits else ""
    short_cert = digits[-4:] if digits else ""
    valid_m = VALID_RE.search(text)
    valid_upto = valid_m.group(1) if valid_m else None
    return {"full": full, "shortCert": short_cert, "validUpto": valid_upto}


def norm_marking(s):
    return re.sub(r"\s+", " ", str(s or "").upper()).strip()


def parse_cert_date(s):
    if not s:
        return None
    try:
        return datetime.strptime(s, "%d %b %Y").date()
    except ValueError:
        try:
            return datetime.strptime(s, "%d %B %Y").date()
        except ValueError:
            return None


def verify_cert_against_row(cert_info, row, today):
    checks = []
    marking_ok = norm_marking(cert_info["full"]) == norm_marking(row["unCertNo1"])
    checks.append({"field": "UN marking string", "ok": marking_ok, "expected": row["unCertNo1"], "found": cert_info["full"]})
    if row["unCertNoShort"]:
        short_ok = cert_info["shortCert"] == row["unCertNoShort"].strip()
        checks.append({"field": "Certificate ref.", "ok": short_ok, "expected": row["unCertNoShort"], "found": cert_info["shortCert"]})
    if cert_info["validUpto"]:
        valid_date = parse_cert_date(cert_info["validUpto"])
        expired = valid_date is not None and valid_date < today
        checks.append({
            "field": "Validity",
            "ok": not expired,
            "expected": "not expired",
            "found": cert_info["validUpto"] + (" (EXPIRED)" if expired else " (valid)"),
        })
    return checks


# ============================================================================
# GROUPING & AGGREGATION
# ============================================================================

def packing_prefix(cert_str):
    s = str(cert_str or "").strip().upper()
    if s.startswith("4G"):
        return "BOX_4G"
    if s.startswith("1A1"):
        return "DRUM_1A1"
    if s.startswith("1A2"):
        return "DRUM_1A2"
    m = re.match(r"^[0-9][A-Z][0-9]?", s)
    return m.group(0) if m else s[:3]


def compute_group_key(row, threshold):
    fp = extract_flash_number(row["flashPoint"])
    bucket = "LT" if (fp is not None and fp < threshold) else "GE"
    psn = row["psn"].upper()
    pkg_code = packing_prefix(row["unCertNo1"])
    mp = row["marinePollutant"]
    un = row["unNumber"]
    return (bucket, psn, pkg_code, mp, un)


def round_up2(n):
    """ROUNDUP-style rounding to 2 decimals, immune to float drift from
    repeated addition. Never understates a shipping weight."""
    fixed = round(n * 1e6) / 1e6
    import math
    return math.ceil(fixed * 100 - 1e-6) / 100


def uniq(items):
    seen = []
    for x in items:
        x = str(x).strip()
        if x and x not in seen:
            seen.append(x)
    return seen


def aggregate_group(rows):
    min_flash = None
    for r in rows:
        fp = extract_flash_number(r["flashPoint"])
        if fp is not None and (min_flash is None or fp < min_flash[0]):
            min_flash = (fp, r["flashPoint"])

    pfx = packing_prefix(rows[0]["unCertNo1"])
    is_drum = pfx.startswith("DRUM")
    pkg_label = "DRUMS" if is_drum else "BOXES"

    outer_total = sum(r["noOfBoxes"] for r in rows)
    inner_total = sum(r["noInTins"] for r in rows)
    gross_total = round_up2(sum(r["grossWt"] for r in rows))
    net_total = round_up2(sum(r["netWt"] for r in rows))

    return {
        "rows": rows,
        "unNumber": rows[0]["unNumber"],
        "psn": rows[0]["psn"],
        "hazClass": rows[0]["hazClass"],
        "pkgGroup": rows[0]["pkgGroup"],
        "marinePollutant": rows[0]["marinePollutant"],
        "ems": ", ".join(uniq(r["ems"] for r in rows)),
        "technicalName": " , ".join(uniq(r["technicalName"] for r in rows)),
        "flashPoint": min_flash[1] if min_flash else "",
        "unPackingCode": " , ".join(uniq(r["unCertNo1"] for r in rows)),
        "outerPackages": f"{outer_total:g} {pkg_label}",
        "isDrum": is_drum,
        "innerPacking": None if is_drum else f"{inner_total:g} TINS",
        "grossWt": f"{gross_total:.2f} KGS",
        "netWt": f"{net_total:.2f} KGS",
        "materials": [r["materialDescription"] for r in rows],
    }


def compute_groups(rows, threshold):
    by_key = {}
    for row in rows:
        key = compute_group_key(row, threshold)
        by_key.setdefault(key, []).append(row)
    return [aggregate_group(rs) for rs in by_key.values()]


# ============================================================================
# VERIFICATION RUNNER
# ============================================================================

def run_verification(rows, msds_docs, cert_docs, today):
    """msds_docs / cert_docs: list of {"name": str, "text": str}"""
    results = []
    for row in rows:
        msds_match = None
        msds_checks = []
        for m in msds_docs:
            if match_msds_to_row(m["text"], row):
                msds_match = m
                break
        if msds_match:
            msds_checks = verify_msds_against_row(msds_match["text"], row)

        cert_match = None
        cert_checks = []
        for c in cert_docs:
            info = c.get("info")
            if info and row["unCertNoShort"] and info["shortCert"] == row["unCertNoShort"].strip():
                cert_match = c
                break
        if cert_match:
            cert_checks = verify_cert_against_row(cert_match["info"], row, today)

        all_checks = msds_checks + cert_checks
        has_error = any(not c["ok"] for c in all_checks)
        has_warning = (msds_match is None) or (cert_match is None)
        status = "ERROR" if has_error else ("WARNING" if has_warning else "OK")

        results.append({
            "row": row, "msds_match": msds_match, "cert_match": cert_match,
            "msds_checks": msds_checks, "cert_checks": cert_checks, "status": status,
        })
    return results


def print_verification_report(results):
    print("\n" + "=" * 78)
    print("VERIFICATION RESULTS")
    print("=" * 78)
    counts = {"OK": 0, "WARNING": 0, "ERROR": 0}
    for v in results:
        counts[v["status"]] += 1
        row = v["row"]
        print(f"\n[{v['status']}] {row['materialDescription']}  (UN {row['unNumber']})")
        print(f"   MSDS: {v['msds_match']['name'] if v['msds_match'] else 'not uploaded'}"
              f"   |   Cert: {v['cert_match']['name'] if v['cert_match'] else 'not uploaded'}")
        for c in v["msds_checks"]:
            if not c["ok"]:
                print(f"   \u2717 MSDS {c['field']} mismatch \u2014 expected {c['expected']}")
        for c in v["cert_checks"]:
            if not c["ok"]:
                print(f"   \u2717 Cert {c['field']} mismatch \u2014 expected {c['expected']}"
                      f"{', found ' + c['found'] if c.get('found') else ''}")
    print("\n" + "-" * 78)
    print(f"Summary: {counts['OK']} OK, {counts['WARNING']} warning, {counts['ERROR']} error"
          f"  (of {len(results)} rows)")
    print("-" * 78)


# ============================================================================
# TEMPLATE-BASED DGDI OUTPUT
# ============================================================================

# Cell map taken directly from the reference DGDI template layout.
GROUP_CELLS = {
    "unNumber": "D36", "grossWt": "H36",
    "psn": "D38", "netWt": "H38",
    "technicalName": "D40",
    "hazClass": "C42", "subClass": "E42",
    "outerPackages": "A43",
    "pkgGroup": "D44",
    "innerPackingLabel": "A44", "innerPacking": "A45",
    "unPackingCode": "D46",
    "ems": "D48",
    "flashPoint": "D50",
    "marinePollutant": "D52",
}
SHIPMENT_CELLS = {
    "shipperLine1": "A9", "shipperLine2": "A10", "shipperLine3": "A11", "shipperLine4": "A12",
    "referenceNumbers": "D9",
    "emergencyContact": "D15",
    "consigneeLine1": "A17", "consigneeLine2": "A18", "consigneeLine3": "A19", "consigneeLine4": "A20",
    "carrier": "D17",
    "bookingNumber": "D19",
    "signatoryCompanyTop": "D22",
    "placeDatePacker": "D25",
    "packerSignatory": "D28",
    "shipNameVoyage": "A31", "portOfLoading": "B31", "containerNumbers": "D31",
    "portOfUnloading": "A33", "finalPlaceDelivery": "B33",
    "signatoryCompanyBottom": "D55",
    "placeDateShipper": "D57",
    "shipperSignatory": "D60",
}

SHIPMENT_FIELDS = [
    "shipperBlock", "consigneeBlock", "referenceNumbers", "emergencyContact",
    "carrier", "bookingNumber", "shipNameVoyage", "containerNumbers",
    "portOfLoading", "portOfUnloading", "finalPlaceDelivery", "placeDate",
    "signatoryCompany", "packerSignatory", "shipperSignatory",
]


def set_cell(ws, addr, value):
    if value in (None, ""):
        ws[addr] = None
        return
    sval = str(value).strip()
    is_num = re.fullmatch(r"-?[0-9]+(\.[0-9]+)?", sval) is not None
    ws[addr] = float(sval) if ("." in sval and is_num) else (int(sval) if is_num else value)


def build_dgd_workbook(template_path, group, shipment):
    wb = openpyxl.load_workbook(template_path)
    ws = wb[wb.sheetnames[0]]

    shipper_lines = (shipment.get("shipperBlock") or "").split("\n")
    consignee_lines = (shipment.get("consigneeBlock") or "").split("\n")

    set_cell(ws, GROUP_CELLS["unNumber"], group["unNumber"])
    set_cell(ws, GROUP_CELLS["grossWt"], group["grossWt"])
    set_cell(ws, GROUP_CELLS["psn"], group["psn"])
    set_cell(ws, GROUP_CELLS["netWt"], group["netWt"])
    set_cell(ws, GROUP_CELLS["technicalName"], group["technicalName"])
    set_cell(ws, GROUP_CELLS["hazClass"], group["hazClass"])
    set_cell(ws, GROUP_CELLS["subClass"], "-")
    set_cell(ws, GROUP_CELLS["outerPackages"], group["outerPackages"])
    set_cell(ws, GROUP_CELLS["pkgGroup"], group["pkgGroup"])
    set_cell(ws, GROUP_CELLS["unPackingCode"], group["unPackingCode"])
    set_cell(ws, GROUP_CELLS["ems"], group["ems"])
    set_cell(ws, GROUP_CELLS["flashPoint"], group["flashPoint"])
    set_cell(ws, GROUP_CELLS["marinePollutant"], group["marinePollutant"])

    if group["innerPacking"]:
        set_cell(ws, GROUP_CELLS["innerPackingLabel"], "INNER PACKING :-")
        set_cell(ws, GROUP_CELLS["innerPacking"], group["innerPacking"])
    else:
        set_cell(ws, GROUP_CELLS["innerPackingLabel"], None)
        set_cell(ws, GROUP_CELLS["innerPacking"], None)

    def sh(key):
        return shipment.get(key) or ""

    set_cell(ws, SHIPMENT_CELLS["shipperLine1"], shipper_lines[0] if len(shipper_lines) > 0 else "")
    set_cell(ws, SHIPMENT_CELLS["shipperLine2"], shipper_lines[1] if len(shipper_lines) > 1 else "")
    set_cell(ws, SHIPMENT_CELLS["shipperLine3"], shipper_lines[2] if len(shipper_lines) > 2 else "")
    set_cell(ws, SHIPMENT_CELLS["shipperLine4"], shipper_lines[3] if len(shipper_lines) > 3 else "")
    set_cell(ws, SHIPMENT_CELLS["referenceNumbers"], sh("referenceNumbers"))
    set_cell(ws, SHIPMENT_CELLS["emergencyContact"], sh("emergencyContact"))
    set_cell(ws, SHIPMENT_CELLS["consigneeLine1"], consignee_lines[0] if len(consignee_lines) > 0 else "")
    set_cell(ws, SHIPMENT_CELLS["consigneeLine2"], consignee_lines[1] if len(consignee_lines) > 1 else "")
    set_cell(ws, SHIPMENT_CELLS["consigneeLine3"], consignee_lines[2] if len(consignee_lines) > 2 else "")
    set_cell(ws, SHIPMENT_CELLS["consigneeLine4"], consignee_lines[3] if len(consignee_lines) > 3 else "")
    set_cell(ws, SHIPMENT_CELLS["carrier"], sh("carrier"))
    set_cell(ws, SHIPMENT_CELLS["bookingNumber"], sh("bookingNumber"))
    set_cell(ws, SHIPMENT_CELLS["signatoryCompanyTop"], sh("signatoryCompany"))
    set_cell(ws, SHIPMENT_CELLS["placeDatePacker"], sh("placeDate"))
    set_cell(ws, SHIPMENT_CELLS["packerSignatory"], sh("packerSignatory"))
    set_cell(ws, SHIPMENT_CELLS["shipNameVoyage"], sh("shipNameVoyage"))
    set_cell(ws, SHIPMENT_CELLS["portOfLoading"], sh("portOfLoading"))
    set_cell(ws, SHIPMENT_CELLS["containerNumbers"], sh("containerNumbers"))
    set_cell(ws, SHIPMENT_CELLS["portOfUnloading"], sh("portOfUnloading"))
    set_cell(ws, SHIPMENT_CELLS["finalPlaceDelivery"], sh("finalPlaceDelivery"))
    set_cell(ws, SHIPMENT_CELLS["signatoryCompanyBottom"], sh("signatoryCompany"))
    set_cell(ws, SHIPMENT_CELLS["placeDateShipper"], sh("placeDate"))
    set_cell(ws, SHIPMENT_CELLS["shipperSignatory"], sh("shipperSignatory"))

    return wb


# ============================================================================
# CLI
# ============================================================================

def load_shipment(path):
    if not path:
        return {k: "" for k in SHIPMENT_FIELDS}
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return {k: data.get(k, "") for k in SHIPMENT_FIELDS}


def write_shipment_template(path):
    template = {k: "" for k in SHIPMENT_FIELDS}
    template["shipperBlock"] = "COMPANY NAME\nADDRESS LINE 1\nADDRESS LINE 2\nCOUNTRY"
    template["consigneeBlock"] = "COMPANY NAME\nADDRESS LINE 1\nADDRESS LINE 2\nCOUNTRY"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(template, f, indent=2)
    print(f"Wrote blank shipment template to {path}")


def main():
    ap = argparse.ArgumentParser(description="DG Declaration Builder")
    ap.add_argument("--annexure", help="Path to the Annexure Excel file")
    ap.add_argument("--template", help="Path to the blank DGDI Excel template")
    ap.add_argument("--msds", nargs="*", default=[], help="MSDS PDF file(s)")
    ap.add_argument("--certs", nargs="*", default=[], help="UN Certificate PDF file(s)")
    ap.add_argument("--shipment", help="Path to a shipment.json (see --make-shipment-template)")
    ap.add_argument("--out", default="./output", help="Output directory (default ./output)")
    ap.add_argument("--threshold", type=float, default=23.0, help="Flash point bucket threshold, degC (default 23)")
    ap.add_argument("--make-shipment-template", metavar="PATH", help="Write a blank shipment.json and exit")
    args = ap.parse_args()

    if args.make_shipment_template:
        write_shipment_template(args.make_shipment_template)
        return

    if not args.annexure or not args.template:
        ap.error("--annexure and --template are required (unless using --make-shipment-template)")

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"Reading annexure: {args.annexure}")
    rows, sheet_name, col_map, score = parse_annexure(args.annexure)
    if not rows:
        print("No usable rows found — check the annexure has the required columns.", file=sys.stderr)
        sys.exit(1)
    print(f"  Parsed {len(rows)} rows from sheet '{sheet_name}' "
          f"({score}/{len(REQUIRED_FIELDS)} required columns matched)")

    msds_docs = []
    for p in args.msds:
        print(f"Reading MSDS: {p}")
        msds_docs.append({"name": Path(p).name, "text": extract_pdf_text(p)})

    cert_docs = []
    for p in args.certs:
        print(f"Reading UN certificate: {p}")
        text = extract_pdf_text(p)
        info = extract_cert_info(text)
        cert_docs.append({"name": Path(p).name, "text": text, "info": info})

    today = date.today()
    results = run_verification(rows, msds_docs, cert_docs, today)
    print_verification_report(results)

    print("\nActive grouping sequence:")
    for i, (label, cond) in enumerate(CHECKPOINTS, 1):
        print(f"  {i}. {label} \u2014 {cond}")
    print(f"  (flash point threshold = {args.threshold}\u00b0C)")

    groups = compute_groups(rows, args.threshold)
    print(f"\n{len(groups)} declaration group(s) from {len(rows)} annexure rows.\n")

    shipment = load_shipment(args.shipment)
    if not args.shipment:
        print("No --shipment file given — vessel/booking/signatory fields will be left "
              "blank in the output for manual completion.\n")

    for i, g in enumerate(groups, 1):
        print(f"DGD-{i}: UN {g['unNumber']} / {g['psn']} / Class {g['hazClass']} "
              f"\u2014 {g['outerPackages']}"
              + (f", {g['innerPacking']}" if g["innerPacking"] else "")
              + f" \u2014 {g['grossWt']} / {g['netWt']}")
        print(f"        products: {', '.join(g['materials'])}")
        wb = build_dgd_workbook(args.template, g, shipment)
        out_path = out_dir / f"DGDI-{i}.xlsx"
        wb.save(out_path)
        print(f"        \u2192 saved {out_path}")

    print(f"\nDone. {len(groups)} file(s) written to {out_dir.resolve()}")


if __name__ == "__main__":
    main()
